#!/bin/bash
# curl http://lesgourg.github.io/class_public/class_public-2.9.0.tar.gz | tar xz
# cd class_public-2.9.0
git clone --depth=1 -b 2.9 https://github.com/lesgourg/class_public.git
cd class_public
PYTHON=python3 make -j all